# Generated by Django 2.2.6 on 2022-09-21 13:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_auto_20220616_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='var_table',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='process',
            name='category',
        ),
        migrations.AddField(
            model_name='process',
            name='category',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), default=list, size=None),
        ),
    ]
