# Generated by Django 2.2.6 on 2022-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_auto_20220921_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='coding',
            field=models.TextField(default=''),
        ),
    ]
