# Generated by Django 2.2.6 on 2022-10-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_processrun_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocessrun',
            name='process_run',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='flow.ProcessRun'),
        ),
    ]
