# Generated by Django 2.2.6 on 2023-01-13 11:52

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_auto_20221028_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderun',
            name='inputs_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端参数组件'),
        ),
    ]
