# Generated by Django 2.2.6 on 2023-02-24 10:03

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_node_inputs_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnoderun',
            name='inputs_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端参数组件'),
        ),
    ]
