# Generated by Django 2.2.6 on 2023-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_subnoderun_inputs_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderun',
            name='subprocess_runtime_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='子流程的运行时id'),
        ),
        migrations.AddField(
            model_name='subnoderun',
            name='subprocess_runtime_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='嵌套子流程的运行时id'),
        ),
    ]
