# Generated by Django 2.2.6 on 2023-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_auto_20230224_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='task_id',
            field=models.IntegerField(default=0, verbose_name='任务ID'),
        ),
    ]
