# Generated by Django 2.2.6 on 2022-09-21 11:20

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='变量表名称')),
                ('description', models.CharField(max_length=255, verbose_name='变量表描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('data', django_mysql.models.JSONField(default=list, verbose_name='变量')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='runtime_var',
            field=django_mysql.models.JSONField(default=dict, verbose_name='运行时变量'),
        ),
        migrations.AddField(
            model_name='task',
            name='var_table',
            field=models.ManyToManyField(to='task.VarTable'),
        ),
    ]
