# Generated by Django 2.2.6 on 2022-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220921_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vartable',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='变量表名称'),
        ),
    ]
