# Generated by Django 2.2.6 on 2022-09-21 15:56

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220921_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='runtime_var',
        ),
        migrations.RemoveField(
            model_name='task',
            name='var_table',
        ),
        migrations.AddField(
            model_name='task',
            name='var_table',
            field=django_mysql.models.JSONField(default=dict, verbose_name='运行时变量'),
        ),
    ]
