# Generated by Django 2.2.6 on 2022-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20220921_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cron_time',
            field=models.TextField(default='', null=True, verbose_name='cron表达式'),
        ),
    ]
