# Generated by Django 2.2.6 on 2022-09-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_auto_20220921_1325'),
        ('task', '0005_auto_20220921_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_tasks', to='flow.Process'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process_run',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='flow.ProcessRun'),
        ),
    ]
