# Generated by Django 2.2.6 on 2022-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220921_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='when_start',
            field=models.CharField(max_length=100, null=True, verbose_name='执行时间'),
        ),
    ]
