# Generated by Django 2.2.6 on 2023-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20220922_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_converge',
            field=models.BooleanField(default=False, verbose_name='记录收敛'),
        ),
    ]
